// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5kfCGHS6c3qHzLfSNfMofeusDetc4VFE',
    appId: '1:32472566149:web:8f312c0dc89a5c73121cec',
    messagingSenderId: '32472566149',
    projectId: 'cinevault-d079b',
    authDomain: 'cinevault-d079b.firebaseapp.com',
    storageBucket: 'cinevault-d079b.firebasestorage.app',
    measurementId: 'G-2TRG84JYM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChVzTaYP61QjzAK0OOXpa-FQaNQHyTNls',
    appId: '1:32472566149:android:1da95fa178df923b121cec',
    messagingSenderId: '32472566149',
    projectId: 'cinevault-d079b',
    storageBucket: 'cinevault-d079b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnc0ydE6IdnmUnv0CrN0QmqidSZNpf4q4',
    appId: '1:32472566149:ios:2f466ad872193cb4121cec',
    messagingSenderId: '32472566149',
    projectId: 'cinevault-d079b',
    storageBucket: 'cinevault-d079b.firebasestorage.app',
    iosBundleId: 'com.example.cineVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnc0ydE6IdnmUnv0CrN0QmqidSZNpf4q4',
    appId: '1:32472566149:ios:2f466ad872193cb4121cec',
    messagingSenderId: '32472566149',
    projectId: 'cinevault-d079b',
    storageBucket: 'cinevault-d079b.firebasestorage.app',
    iosBundleId: 'com.example.cineVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5kfCGHS6c3qHzLfSNfMofeusDetc4VFE',
    appId: '1:32472566149:web:058178ff2ba57c9b121cec',
    messagingSenderId: '32472566149',
    projectId: 'cinevault-d079b',
    authDomain: 'cinevault-d079b.firebaseapp.com',
    storageBucket: 'cinevault-d079b.firebasestorage.app',
    measurementId: 'G-EQH6XJR9MP',
  );
}
