name: Flutter CI/CD with Firebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build, Test & Deploy to Firebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.29.0

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Decode Firebase Service Account Key
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}' > $HOME/firebase-service-account.json

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Debug Firebase Authentication
        run: |
          cat $HOME/firebase-service-account.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Authenticate Firebase CLI
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-service-account.json"
          firebase projects:list
          firebase use --add ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Upload APK to Firebase App Distribution
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-service-account.json"
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --project ${{ secrets.FIREBASE_PROJECT_ID }}
