name: Flutter CI/CD with Firebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build, Test & Deploy to Firebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Setup Java Home
        run: echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.29.0

      - name: Install Dependencies
        run: flutter pub get

      - name: Ensure .env file exists
        run: mkdir -p assets/config && touch assets/config/.env

      - name: Force Java Path in Gradle
        run: echo "org.gradle.java.home=$JAVA_HOME" >> android/gradle.properties

      - name: Build APK
        run: flutter build apk --release

      - name: Set up Firebase authentication
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}' > $HOME/firebase-service-account.json

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Authenticate Firebase CLI
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-service-account.json"
          firebase projects:list
          firebase use --add ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Upload APK to Firebase App Distribution
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-service-account.json"
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --project ${{ secrets.FIREBASE_PROJECT_ID }} \
            --groups "testers-group"
